services:
    eliza:
        command: ["pnpm", "start"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./data:/app/data 
        ports:
            - "3000:3000"
        restart: always
